(require 'key-chord)
(key-chord-define-global ";b" 'ido-switch-buffer)
(key-chord-define-global ";r" 'recentf-ido-find-file)
(key-chord-define-global ";f" 'ido-find-file)
(key-chord-define-global ";g" 'magit-status)
(key-chord-define-global ";j" 'ace-jump-word-mode)
(key-chord-define-global ";l" 'ace-jump-line-mode)
(key-chord-define-global ";k" 'ace-jump-char-mode)
(key-chord-define-global ";u" 'undo-tree-visualize)
(key-chord-define-global ";," 'fill-paragraph)
(key-chord-define-global ";o" 'magit-in-perspective)
(key-chord-define-global ";d" 'dired-jump-other-window)
(key-chord-define-global ";a" 'ack-and-a-half)
(key-chord-mode +1)
