(require 'key-chord)
(key-chord-define-global "id" 'ido-switch-buffer)
(key-chord-define-global "ir" 'recentf-ido-find-file)
(key-chord-define-global "if" 'ido-find-file)
(key-chord-define-global "mg" 'magit-status)
(key-chord-define-global "aw" 'ace-jump-word-mode)
(key-chord-define-global "al" 'ace-jump-line-mode)
(key-chord-define-global "ac" 'ace-jump-char-mode)
(key-chord-define-global "un" 'undo-tree-visualize)
(key-chord-define-global "fp" 'fill-paragraph)
(key-chord-define-global "mi" 'magit-in-perspective)
(key-chord-define-global "dj" 'dired-jump-other-window)
(key-chord-define-global "aa" 'ack-and-a-half)
(key-chord-mode +1)
